Algoritmo "Questão 04"
// Fazer um programa que pergunte um número inteiro
// e apresente o seu antecessor e seu sucessor.

Var
// Seção de Declarações das variáveis 
   num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Informe um número inteiro")
   leia(num)
   escreval("o antecessor desse número é ",num - 1)
   escreval("O sucessor desse número é ",num + 1)

Fimalgoritmo